spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
    ssl:
      enabled: true

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}   # Render injects PORT automatically
  servlet:
    context-path: /journal

weather:
  api:
    key: ${WEATHER_API_KEY}

springdoc:
  swagger-ui:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,threaddump,httptrace
  endpoint:
    health:
      show-details: always
